### ISSUE TITLE
add `exporter_version` label

### ISSUE THREAD

**Issue by kworr** [sapcc/ntp_exporter#12]
Misses two nice metrics:

    ntp_version 1.1.1
    ntp_up{server="127.0.0.1"} 1

Would be nice to have a track on whats installed where (I have a few hundreds of 'em) and also detect whether exporter is actually running. Right now on hosts with chrony it just returns nothing.

**Comment by kworr** [comment]
Ah, might be done easier:

    ntp_up{exporter_version="1.1.1", server="127.0.0.1"} 1

**Comment by majewsky** [comment]
You can see whether the exporter is running by checking the `up` metric generated by Prometheus. The exact set of labels depends on your scrape config.

**Comment by kworr** [comment]
Um, that's nice. Thank you.

**Comment by majewsky** [comment]
I'll leave the issue open for the other part of the request, about adding an `exporter_version` label to the metrics.
