### ISSUE TITLE
Duration not parsing correctly

### ISSUE THREAD

**Issue by davehayes** [sapcc/ntp_exporter#127]
On your latest tag v2.7.0 as well as master and tag v2.6.1 the following happens:

```
> curl 'http://127.0.0.1:12345/metrics?duration=10s&protocol=4&target=time.cloudflare.com'
time: invalid duration ""
> echo wat\?
wat?
> curl 'http://127.0.0.1:12345/metrics?duration=10&protocol=4&target=time.cloudflare.com'
time: missing unit in duration "10"
```

Am  I missing something here? I  am on FreeBSD 13.4 and I have installed  go 1.23 here. This  is a manual build to keep ports tree issues out of the direct way, but the same thing  happens if I make a port skeleton and build this  package inside the ports  system.

BTW tag v2.5.0 works with go121 just fine.

**Comment by SuperSandro2000** [comment]
> duration=10&protocol

you are missing the s there.

> BTW tag v2.5.0 works with go121 just fine.

Yeah? The build was built with go 1.21.4, see the changelog:

> The Go used to build the prebuilt binaries was updated to version 1.21.4.

**Comment by SuperSandro2000** [comment]
The parsing error came from the high_drift parameter and is fixed in https://github.com/sapcc/ntp_exporter/releases/tag/v2.7.1

**Comment by davehayes** [comment]
Nice! Thanks, I'll check it out. 

Note that I build this two ways and do not use your prebuilt binaries.

**Comment by SuperSandro2000** [comment]
> Note that I build this two ways and do not use your prebuilt binaries.

That shouldn't really make any difference. The binaries are just there for convince.
