### ISSUE TITLE
Make release with compiled binary

### ISSUE THREAD

**Issue by elcomtik** [sapcc/ntp_exporter#13]
It would be useful if you add a compiled binary to each release. Most of Prometheus exporters projects do it(https://github.com/prometheus/node_exporter/releases). I think it would help to simplify installation to a lot of people.

At least linux-amd64 and linux-386 architectures would be necessary

**Comment by majewsky** [comment]
I added a config for goreleaser. The 2.0.0 release has compiled binaries attached to it.

**Comment by elcomtik** [comment]
Thanks
