### ISSUE TITLE
Add support for multiple timehosts

### ISSUE THREAD

**Issue by Savemech** [sapcc/ntp_exporter#2]
Hi there, could you please explain how this exporter differs from node_exproter with enabled ntp collector?

**Comment by reimannf** [comment]
Hi. ntp for the node exporter is deprecated https://github.com/prometheus/node_exporter#deprecated so we started that one.

**Comment by Savemech** [comment]
Oh, i see.
So then, any chance to implement multiple servers support:question:

**Comment by reimannf** [comment]
Would be a valuable enhancement. Nevertheless don't expect it to happen very soon.

**Comment by majewsky** [comment]
@Savemech If you want to modify the exporter to accept multiple NTP servers, and send each metric (drift and stratum) multiple times with a `server` label, I will happily review and merge the pull request.

**Comment by Savemech** [comment]
@majewsky i'm not so that cool to code this through, even if i can, the code would be ugly, and definitely not ready for use in production systems of many people intend to use

**Comment by dhalturin** [comment]
https://github.com/sapcc/ntp_exporter/pull/11

**Comment by Savemech** [comment]
oh wow
