### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by lindhor** [sapcc/ntp_exporter#25]
I wonder if you would consider adding additional metrics to closer match what the node_exporter provide. If I understand your codebase correctly you already get additional values back from the ntp server part of the Query response. I.e. these values (and node_exporters corresponding metric in parentheses)
- RTT (node_ntp_rtt)
- ReferenceTime (node_ntp_reference_timestamp_seconds)
- RootDelay (node_ntp_root_delay)
- RootDispersion (node_ntp_root_dispersion)
- Leap (node_ntp_leap)

You might also want to add
- Precision
- KissCode (as a label)

I also would like to say I really like your approach of being able to remotely "blackbox like" poll ntp servers. That is very useful and a great feature compared to node_exporter. It is also a big benefit that ntp_exporter runs on different OS:es compared to node_exporter only on Unix-like ones.

**Comment by majewsky** [comment]
The current set of metrics does what we need it to do, so we don't plan on extending it ourselves. But if you (or anyone else) wants to send a PR, we will look at it.
