### ISSUE TITLE
Couldn't get NTP drift

### ISSUE THREAD

**Issue by nsaud01** [sapcc/ntp_exporter#4]
I have all UDP ports open and my docker run command is as follows:  

docker run -d -p 9102:9100 \
  --name ntp-exporter \
  --restart unless-stopped \
  ntp-exporter:latest \
  -ntp.server=0.amazon.pool.ntp.org

No matter what I put as the -ntp.server I get constant timeouts:

8/3/2017 3:11:33 PMINFO[0000] Starting ntp_exporter v1.0-7-gf28483e         source="main.go:58"
8/3/2017 3:11:33 PMINFO[0000] Listening on :9100                            source="main.go:74"
8/3/2017 3:35:22 PMERRO[1429] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:52130->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:35:52 PMERRO[1459] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:35646->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:36:07 PMERRO[1474] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:51390->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:36:37 PMERRO[1504] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:41850->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:37:07 PMERRO[1534] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:55438->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:37:22 PMERRO[1549] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:51386->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:37:52 PMERRO[1579] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:36797->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:38:37 PMERRO[1624] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:40700->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:38:52 PMERRO[1639] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:50951->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:39:22 PMERRO[1669] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:54118->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:39:37 PMERRO[1684] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:32964->167.160.84.183:123: i/o timeout  source="collector.go:73"
8/3/2017 3:39:52 PMERRO[1699] couldn't get NTP drift: couldn't get NTP drift: read udp 10.42.0.73:39937->167.160.84.183:123: i/o timeout  source="collector.go:73"

Am I doing something wrong? I really want this to work.

**Comment by majewsky** [comment]
Hi. Sorry for not noticing your submission earlier.

Anyway, the "i/o timeout" error sounds like a network error. Can you check if other NTP clients (sntp, ntpdate, etc.) can reach the desired timeserver, preferably also from inside a container?

**Comment by majewsky** [comment]
I'll assume that this was a network error and not caused on our side.
