### ISSUE TITLE
[Feature] Select active ntp peer automatically

### ISSUE THREAD

**Issue by PandaFoss** [sapcc/ntp_exporter#77]
**Context:** If I am not mistaken, the `-ntp.server` option must be passed to the exporter to generate the metrics based on that NTP server. The problem arises when a server has more than one NTP peer, and we cannot know in advance which one is the active one. 

**Question:** Is it possible to add to the exporter the ability to detect inside the server which one is the active peer and generate the metrics based on that server?

**Comment by majewsky** [comment]
That would require knowing which NTP client software is being used, and at that point, I'd recommend rather just instrumenting the NTP client itself. This exporter is intended to be independent of the NTP client, to act as an independent verifier.

From what I understand about the usecase that you describe, I would recommend running the exporter against all possible peers, and alerting on when all peers slip away too far, e.g. `absent((ntp_drift_seconds{hostname="foo"} < 0.2) > -0.2)` or `abs(avg by (hostname) (ntp_drift_seconds)) > 0.2` or something like that.
