### ISSUE TITLE
The meaning of indicators：ntp_drift_seconds

### ISSUE THREAD

**Issue by yy549159265** [sapcc/ntp_exporter#79]
Difference between system time and NTP time

May I ask what the system time and NTP time represent

**Comment by SuperSandro2000** [comment]
ntp_drift_seconds is based on ClockOffset of the [ntp library](https://github.com/beevik/ntp) we are using.

system time is the time of the linux server where the exporter is running and ntp time is what the ntp server reported. offset or drift is the estimated difference between that.
